/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Advogado;
import control.ClientePf;
import control.ClientePj;
import dao.DAOSistema;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import util.GerarDocumentos;

/**
 *
 * @author Nortton
 */
public class IFrmGerarRelatorios extends javax.swing.JInternalFrame {

    int[] vetorCliente;
    GerarDocumentos gerar = null;
    Advogado aMaster=null;
    
    public IFrmGerarRelatorios(Advogado a) {
        initComponents();
        aMaster = a;
    }
    
    public void carregarcbxCliente(){
        String sql="";
        if(rbPFisica.isSelected() && !rbPJuridica.isSelected()){
            sql="from ClientePf where ativo = '1' order by nome";
            Session s=null;
            try{
                s = DAOSistema.getSessionFactory().openSession();
                s.beginTransaction();

                Query q = s.createQuery(sql);
                List l = q.list();
                Iterator i = l.iterator();
                
                vetorCliente = new int[l.size()];

                ClientePf c;
                cbxCliente.removeAllItems();
                int cont=0;

                while(i.hasNext()){
                    c=(ClientePf)i.next();
                    cbxCliente.addItem(c.getNome());
                    vetorCliente[cont]=c.getId();
                    cont++;
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(IFrmGerarRelatorios.this, ex);
                ex.printStackTrace();
            }finally{
                s.getTransaction().commit();
                s.close();
            }
            AutoCompleteDecorator.decorate(cbxCliente);
        }else{
            sql="from ClientePj where ativo = '1' order by nomeFantasia";
            Session s = null;
            try{
                s = DAOSistema.getSessionFactory().openSession();
                s.beginTransaction();

                Query q = s.createQuery(sql);
                List l = q.list();
                Iterator i = l.iterator();

                vetorCliente = new int[l.size()];
                
                ClientePj c;
                cbxCliente.removeAllItems();
                int cont=0;

                while(i.hasNext()){
                    c=(ClientePj)i.next();
                    cbxCliente.addItem(c.getNomeFantasia());
                    vetorCliente[cont]=c.getId();
                    cont++;
                }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(IFrmGerarRelatorios.this, ex);
                ex.printStackTrace();
            }finally{
                s.getTransaction().commit();
                s.close();
            }
            AutoCompleteDecorator.decorate(cbxCliente);
        }
    }
    
    private void gerarRel(char value){
        gerar = new GerarDocumentos();
        if(value=='F'){
            ClientePf cliente = new ClientePf();
            cliente.setId(vetorCliente[cbxCliente.getSelectedIndex()]);
            if(chkDados.isSelected()){
                //gerar.gerar("from ClientePf where id =" +idCliente, "src/relatorios/relClientePf.jasper");
            }
            if(chkHonorarios.isSelected()){
                //gerar.gerarRelatorios("from ClientePf where id =" +idCliente, "ARQUIVO");
            }
            if(chkPobreza.isSelected()){
                gerar.gerarDeclaracaoPobreza(cliente, aMaster);
            }
            if(chkProcuracao.isSelected()){
                gerar.gerarProcuracaoPf(cliente, aMaster);
            }
        }else{
            ClientePj cliente = new ClientePj();
            cliente.setId(vetorCliente[cbxCliente.getSelectedIndex()]);
            if(chkDados.isSelected()){
                //gerar.gerarRelatorios("from ClientePj where id =" +idCliente, "src/relatorios/relClientePj.jasper");
            }
        }
    }
    
    private void limparCampos(){
        chkDados.setSelected(false);
        chkHonorarios.setSelected(false);
        chkPobreza.setSelected(false);
        chkProcuracao.setSelected(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbPFisica = new javax.swing.JRadioButton();
        rbPJuridica = new javax.swing.JRadioButton();
        cbxCliente = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkProcuracao = new javax.swing.JCheckBox();
        chkHonorarios = new javax.swing.JCheckBox();
        chkPobreza = new javax.swing.JCheckBox();
        chkDados = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatorio de Documentacao");

        jLabel1.setText("Selecione um Cliente:");

        buttonGroup1.add(rbPFisica);
        rbPFisica.setText("Pessoa Fisica");
        rbPFisica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPFisicaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbPJuridica);
        rbPJuridica.setText("Pessoa Juridica");

        jLabel2.setText("Selecione um tipo de relatorio:");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        chkProcuracao.setText("Procuração");

        chkHonorarios.setText("Contrato de Honorários");
        chkHonorarios.setEnabled(false);

        chkPobreza.setText("Declaração de pobreza");

        chkDados.setText("Dados cadastrais");
        chkDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPJuridica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkProcuracao)
                                .addGap(18, 18, 18)
                                .addComponent(chkPobreza))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(chkHonorarios)
                        .addGap(18, 18, 18)
                        .addComponent(chkDados)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPFisica)
                    .addComponent(rbPJuridica)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkProcuracao)
                    .addComponent(chkPobreza)
                    .addComponent(chkHonorarios)
                    .addComponent(chkDados))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        if(rbPFisica.isSelected() && !rbPJuridica.isSelected()){
            //Fisica
            gerarRel('F');
        }else if(!rbPFisica.isSelected() && rbPJuridica.isSelected()){
            //Juridica
            gerarRel('J');
        }else{
            JOptionPane.showMessageDialog(IFrmGerarRelatorios.this, "Selecione Pessoa Fisica ou Juridica!");
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void rbPFisicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPFisicaItemStateChanged
        // TODO add your handling code here:
        carregarcbxCliente();
    }//GEN-LAST:event_rbPFisicaItemStateChanged

    private void chkDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDadosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JCheckBox chkDados;
    private javax.swing.JCheckBox chkHonorarios;
    private javax.swing.JCheckBox chkPobreza;
    private javax.swing.JCheckBox chkProcuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbPFisica;
    private javax.swing.JRadioButton rbPJuridica;
    // End of variables declaration//GEN-END:variables
}
