-- MySQL Script generated by MySQL Workbench
-- Fri Nov 24 02:40:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema advocacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema advocacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `advocacia` DEFAULT CHARACTER SET utf8 ;
USE `advocacia` ;

-- -----------------------------------------------------
-- Table `advocacia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargo` CHAR(1) NOT NULL DEFAULT 's',
  `ativo` TINYINT NOT NULL,
  `acesso` CHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(80) NOT NULL,
  `numero` VARCHAR(6) NOT NULL DEFAULT 'S/N',
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(60) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `email` VARCHAR(80) NULL,
  `tel` VARCHAR(11) NULL,
  `cel` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`advogado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`advogado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `CodOAB` VARCHAR(6) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `nomeAdvocacia` VARCHAR(100) NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `OABAdvogado_UNIQUE` (`CodOAB` ASC),
  INDEX `fk_advogado_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_advogado_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_advogado_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `advocacia`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_advogado_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `advocacia`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `advogado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_funcionario_advogado1_idx` (`advogado_id` ASC),
  CONSTRAINT `fk_funcionario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `advocacia`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`cliente_pf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`cliente_pf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` MEDIUMTEXT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `nomePai` VARCHAR(100) NULL,
  `nomeMae` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(9) NOT NULL,
  `orgao` VARCHAR(5) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `d_nasc` DATE NOT NULL,
  `estadoCivil` VARCHAR(13) NOT NULL,
  `empresa` VARCHAR(50) NULL,
  `profissao` VARCHAR(45) NULL,
  `ctps` VARCHAR(11) NULL,
  `pis` VARCHAR(11) NULL,
  `pessoa_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  INDEX `fk_cliente_pf_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_cliente_pf_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `advocacia`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`cliente_pj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`cliente_pj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeFantasia` VARCHAR(100) NOT NULL,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `inscricaoMun` VARCHAR(45) NULL,
  `inscricaoEst` VARCHAR(45) NULL,
  `pessoa_id` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_pj_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_cliente_pj_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `advocacia`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`processo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`processo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `outrosEnvolvidos` TEXT(1000) NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `numeroProcesso` INT NOT NULL,
  `juizoNum` INT NOT NULL,
  `juizoVara` VARCHAR(20) NOT NULL,
  `juizoForo` VARCHAR(60) NOT NULL,
  `nomeAcao` VARCHAR(45) NOT NULL,
  `valorCausa` DOUBLE NOT NULL,
  `distribuido` DATE NOT NULL,
  `movimentacao` LONGTEXT NULL,
  `advogado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_processo_advogado1_idx` (`advogado_id` ASC),
  CONSTRAINT `fk_processo_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` VARCHAR(12) NULL,
  `detalhes` MEDIUMTEXT NULL,
  `notificarEmail` TINYINT NOT NULL,
  `ultimaVeificacao` DATE NOT NULL,
  `checkDataEnvio` CHAR(3) NULL,
  `local` VARCHAR(100) NOT NULL,
  `advogado_id` INT NOT NULL,
  `processo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_advogado1_idx` (`advogado_id` ASC),
  INDEX `fk_agenda_processo1_idx` (`processo_id` ASC),
  CONSTRAINT `fk_agenda_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_processo1`
    FOREIGN KEY (`processo_id`)
    REFERENCES `advocacia`.`processo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`financeiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(1) NOT NULL,
  `futuro` DATE NOT NULL,
  `presente` DATE NULL,
  `valor` DOUBLE NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `parcelaTotal` INT NOT NULL,
  `parcela` INT NULL,
  `valorParcela` DOUBLE NULL,
  `porcentagemHonorario` DOUBLE NULL,
  `advogado_id` INT NOT NULL,
  `processo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_financeiro_advogado1_idx` (`advogado_id` ASC),
  INDEX `fk_financeiro_processo1_idx` (`processo_id` ASC),
  CONSTRAINT `fk_financeiro_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financeiro_processo1`
    FOREIGN KEY (`processo_id`)
    REFERENCES `advocacia`.`processo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_agenda_pf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_agenda_pf` (
  `cliente_pf_id` INT NOT NULL,
  `agenda_id` INT NOT NULL,
  INDEX `fk_tbl_agenda_pf_cliente_pf1_idx` (`cliente_pf_id` ASC),
  INDEX `fk_tbl_agenda_pf_agenda1_idx` (`agenda_id` ASC),
  CONSTRAINT `fk_tbl_agenda_pf_cliente_pf1`
    FOREIGN KEY (`cliente_pf_id`)
    REFERENCES `advocacia`.`cliente_pf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_agenda_pf_agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `advocacia`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_agenda_pj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_agenda_pj` (
  `agenda_id` INT NOT NULL,
  `cliente_pj_id` INT NOT NULL,
  INDEX `fk_tbl_agenda_pj_agenda1_idx` (`agenda_id` ASC),
  INDEX `fk_tbl_agenda_pj_cliente_pj1_idx` (`cliente_pj_id` ASC),
  CONSTRAINT `fk_tbl_agenda_pj_agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `advocacia`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_agenda_pj_cliente_pj1`
    FOREIGN KEY (`cliente_pj_id`)
    REFERENCES `advocacia`.`cliente_pj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_processo_pf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_processo_pf` (
  `processo_id` INT NOT NULL,
  `cliente_pf_id` INT NOT NULL,
  INDEX `fk_tbl_processo_pf_processo1_idx` (`processo_id` ASC),
  INDEX `fk_tbl_processo_pf_cliente_pf1_idx` (`cliente_pf_id` ASC),
  CONSTRAINT `fk_tbl_processo_pf_processo1`
    FOREIGN KEY (`processo_id`)
    REFERENCES `advocacia`.`processo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_processo_pf_cliente_pf1`
    FOREIGN KEY (`cliente_pf_id`)
    REFERENCES `advocacia`.`cliente_pf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_processo_pj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_processo_pj` (
  `processo_id` INT NOT NULL,
  `cliente_pj_id` INT NOT NULL,
  INDEX `fk_tbl_processo_pj_processo1_idx` (`processo_id` ASC),
  INDEX `fk_tbl_processo_pj_cliente_pj1_idx` (`cliente_pj_id` ASC),
  CONSTRAINT `fk_tbl_processo_pj_processo1`
    FOREIGN KEY (`processo_id`)
    REFERENCES `advocacia`.`processo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_processo_pj_cliente_pj1`
    FOREIGN KEY (`cliente_pj_id`)
    REFERENCES `advocacia`.`cliente_pj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_financeiro_pf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_financeiro_pf` (
  `cliente_pf_id` INT NOT NULL,
  `financeiro_id` INT NOT NULL,
  INDEX `fk_tbl_financeiro_pf_cliente_pf1_idx` (`cliente_pf_id` ASC),
  INDEX `fk_tbl_financeiro_pf_financeiro1_idx` (`financeiro_id` ASC),
  CONSTRAINT `fk_tbl_financeiro_pf_cliente_pf1`
    FOREIGN KEY (`cliente_pf_id`)
    REFERENCES `advocacia`.`cliente_pf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_financeiro_pf_financeiro1`
    FOREIGN KEY (`financeiro_id`)
    REFERENCES `advocacia`.`financeiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_financeiro_pj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_financeiro_pj` (
  `cliente_pj_id` INT NOT NULL,
  `financeiro_id` INT NOT NULL,
  INDEX `fk_tbl_financeiro_pj_cliente_pj1_idx` (`cliente_pj_id` ASC),
  INDEX `fk_tbl_financeiro_pj_financeiro1_idx` (`financeiro_id` ASC),
  CONSTRAINT `fk_tbl_financeiro_pj_cliente_pj1`
    FOREIGN KEY (`cliente_pj_id`)
    REFERENCES `advocacia`.`cliente_pj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_financeiro_pj_financeiro1`
    FOREIGN KEY (`financeiro_id`)
    REFERENCES `advocacia`.`financeiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_adv_cpf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_adv_cpf` (
  `advogado_id` INT NOT NULL,
  `cliente_pf_id` INT NOT NULL,
  INDEX `fk_tbl_adv_cpf_advogado1_idx` (`advogado_id` ASC),
  INDEX `fk_tbl_adv_cpf_cliente_pf1_idx` (`cliente_pf_id` ASC),
  CONSTRAINT `fk_tbl_adv_cpf_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_adv_cpf_cliente_pf1`
    FOREIGN KEY (`cliente_pf_id`)
    REFERENCES `advocacia`.`cliente_pf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advocacia`.`tbl_adv_cpj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advocacia`.`tbl_adv_cpj` (
  `advogado_id` INT NOT NULL,
  `cliente_pj_id` INT NOT NULL,
  INDEX `fk_tbl_adv_cpj_advogado1_idx` (`advogado_id` ASC),
  INDEX `fk_tbl_adv_cpj_cliente_pj1_idx` (`cliente_pj_id` ASC),
  CONSTRAINT `fk_tbl_adv_cpj_advogado1`
    FOREIGN KEY (`advogado_id`)
    REFERENCES `advocacia`.`advogado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_adv_cpj_cliente_pj1`
    FOREIGN KEY (`cliente_pj_id`)
    REFERENCES `advocacia`.`cliente_pj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
