package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private Integer id;
     private Advogado advogado;
     private Processo processo;
     private Date data;
     private String hora;
     private String detalhes;
     private byte notificarEmail;
     private Date ultimaVeificacao;
     private String checkDataEnvio;
     private String local;
     private Set tblAgendaPfs = new HashSet(0);
     private Set tblAgendaPjs = new HashSet(0);

    public Agenda() {
    }

	
    public Agenda(Advogado advogado, Processo processo, Date data, byte notificarEmail, Date ultimaVeificacao, String local) {
        this.advogado = advogado;
        this.processo = processo;
        this.data = data;
        this.notificarEmail = notificarEmail;
        this.ultimaVeificacao = ultimaVeificacao;
        this.local = local;
    }
    
    public Agenda(Advogado advogado, Processo processo, Date data, String hora, String detalhes, byte notificarEmail, Date ultimaVeificacao, String checkDataEnvio, String local) {
       this.advogado = advogado;
       this.processo = processo;
       this.data = data;
       this.hora = hora;
       this.detalhes = detalhes;
       this.notificarEmail = notificarEmail;
       this.ultimaVeificacao = ultimaVeificacao;
       this.checkDataEnvio = checkDataEnvio;
       this.local = local;
    }
    
    public Agenda(Advogado advogado, Processo processo, Date data, String hora, String detalhes, byte notificarEmail, Date ultimaVeificacao, String checkDataEnvio, String local, Set tblAgendaPfs, Set tblAgendaPjs) {
       this.advogado = advogado;
       this.processo = processo;
       this.data = data;
       this.hora = hora;
       this.detalhes = detalhes;
       this.notificarEmail = notificarEmail;
       this.ultimaVeificacao = ultimaVeificacao;
       this.checkDataEnvio = checkDataEnvio;
       this.local = local;
       this.tblAgendaPfs = tblAgendaPfs;
       this.tblAgendaPjs = tblAgendaPjs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Advogado getAdvogado() {
        return this.advogado;
    }
    
    public void setAdvogado(Advogado advogado) {
        this.advogado = advogado;
    }
    public Processo getProcesso() {
        return this.processo;
    }
    
    public void setProcesso(Processo processo) {
        this.processo = processo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getDetalhes() {
        return this.detalhes;
    }
    
    public void setDetalhes(String detalhes) {
        this.detalhes = detalhes;
    }
    public byte getNotificarEmail() {
        return this.notificarEmail;
    }
    
    public void setNotificarEmail(byte notificarEmail) {
        this.notificarEmail = notificarEmail;
    }
    public Date getUltimaVeificacao() {
        return this.ultimaVeificacao;
    }
    
    public void setUltimaVeificacao(Date ultimaVeificacao) {
        this.ultimaVeificacao = ultimaVeificacao;
    }
    public String getCheckDataEnvio() {
        return this.checkDataEnvio;
    }
    
    public void setCheckDataEnvio(String checkDataEnvio) {
        this.checkDataEnvio = checkDataEnvio;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public Set getTblAgendaPfs() {
        return this.tblAgendaPfs;
    }
    
    public void setTblAgendaPfs(Set tblAgendaPfs) {
        this.tblAgendaPfs = tblAgendaPfs;
    }
    public Set getTblAgendaPjs() {
        return this.tblAgendaPjs;
    }
    
    public void setTblAgendaPjs(Set tblAgendaPjs) {
        this.tblAgendaPjs = tblAgendaPjs;
    }




}


