package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientePj generated by hbm2java
 */
public class ClientePj  implements java.io.Serializable {


     private Integer id;
     private Pessoa pessoa;
     private String nomeFantasia;
     private String razaoSocial;
     private String cnpj;
     private String inscricaoMun;
     private String inscricaoEst;
     private byte ativo;
     private Set tblAgendaPjs = new HashSet(0);
     private Set tblFinanceiroPjs = new HashSet(0);
     private Set tblAdvCpjs = new HashSet(0);
     private Set tblProcessoPjs = new HashSet(0);

    public ClientePj() {
    }
    
    public String[] getCliente(){
        return new String[]{
            String.valueOf(id),
            razaoSocial,
            nomeFantasia,
            cnpj,
            pessoa.getEndereco(),
            pessoa.getCel()
        };
    }

	
    public ClientePj(Pessoa pessoa, String nomeFantasia, String razaoSocial, String cnpj, byte ativo) {
        this.pessoa = pessoa;
        this.nomeFantasia = nomeFantasia;
        this.razaoSocial = razaoSocial;
        this.cnpj = cnpj;
        this.ativo = ativo;
    }
    public ClientePj(Pessoa pessoa, String nomeFantasia, String razaoSocial, String cnpj, String inscricaoMun, String inscricaoEst, byte ativo) {
       this.pessoa = pessoa;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.inscricaoMun = inscricaoMun;
       this.inscricaoEst = inscricaoEst;
       this.ativo = ativo;
    }
    public ClientePj(Pessoa pessoa, String nomeFantasia, String razaoSocial, String cnpj, String inscricaoMun, String inscricaoEst, byte ativo, Set tblAgendaPjs, Set tblFinanceiroPjs, Set tblAdvCpjs, Set tblProcessoPjs) {
       this.pessoa = pessoa;
       this.nomeFantasia = nomeFantasia;
       this.razaoSocial = razaoSocial;
       this.cnpj = cnpj;
       this.inscricaoMun = inscricaoMun;
       this.inscricaoEst = inscricaoEst;
       this.ativo = ativo;
       this.tblAgendaPjs = tblAgendaPjs;
       this.tblFinanceiroPjs = tblFinanceiroPjs;
       this.tblAdvCpjs = tblAdvCpjs;
       this.tblProcessoPjs = tblProcessoPjs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getInscricaoMun() {
        return this.inscricaoMun;
    }
    
    public void setInscricaoMun(String inscricaoMun) {
        this.inscricaoMun = inscricaoMun;
    }
    public String getInscricaoEst() {
        return this.inscricaoEst;
    }
    
    public void setInscricaoEst(String inscricaoEst) {
        this.inscricaoEst = inscricaoEst;
    }
    public byte getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(byte ativo) {
        this.ativo = ativo;
    }
    public Set getTblAgendaPjs() {
        return this.tblAgendaPjs;
    }
    
    public void setTblAgendaPjs(Set tblAgendaPjs) {
        this.tblAgendaPjs = tblAgendaPjs;
    }
    public Set getTblFinanceiroPjs() {
        return this.tblFinanceiroPjs;
    }
    
    public void setTblFinanceiroPjs(Set tblFinanceiroPjs) {
        this.tblFinanceiroPjs = tblFinanceiroPjs;
    }
    public Set getTblAdvCpjs() {
        return this.tblAdvCpjs;
    }
    
    public void setTblAdvCpjs(Set tblAdvCpjs) {
        this.tblAdvCpjs = tblAdvCpjs;
    }
    public Set getTblProcessoPjs() {
        return this.tblProcessoPjs;
    }
    
    public void setTblProcessoPjs(Set tblProcessoPjs) {
        this.tblProcessoPjs = tblProcessoPjs;
    }




}


