package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private String logradouro;
     private String numero;
     private String bairro;
     private String complemento;
     private String cidade;
     private String estado;
     private String cep;
     private String email;
     private String tel;
     private String cel;
     private Set advogados = new HashSet(0);
     private Set clientePjs = new HashSet(0);
     private Set clientePfs = new HashSet(0);

    public Pessoa() {
    }

    public String getEndereco(){
        String txt="";
        txt+=logradouro;
        if(!numero.equals("")){
            txt+=", "+numero;
        }
        if(!complemento.equals("")){
            txt+=", "+complemento;
        }
        txt+=", "+bairro+", "+cidade+ "-"+estado;
        return txt;
    }
	
    public Pessoa(String logradouro, String numero, String bairro, String cidade, String estado, String cep) {
        this.logradouro = logradouro;
        this.numero = numero;
        this.bairro = bairro;
        this.cidade = cidade;
        this.estado = estado;
        this.cep = cep;
    }
    public Pessoa(String logradouro, String numero, String bairro, String complemento, String cidade, String estado, String cep, String email, String tel, String cel) {
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.email = email;
       this.tel = tel;
       this.cel = cel;
    }
    
    public Pessoa(String logradouro, String numero, String bairro, String complemento, String cidade, String estado, String cep, String email, String tel, String cel, Set advogados, Set clientePjs, Set clientePfs) {
       this.logradouro = logradouro;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cidade = cidade;
       this.estado = estado;
       this.cep = cep;
       this.email = email;
       this.tel = tel;
       this.cel = cel;
       this.advogados = advogados;
       this.clientePjs = clientePjs;
       this.clientePfs = clientePfs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }
    public Set getAdvogados() {
        return this.advogados;
    }
    
    public void setAdvogados(Set advogados) {
        this.advogados = advogados;
    }
    public Set getClientePjs() {
        return this.clientePjs;
    }
    
    public void setClientePjs(Set clientePjs) {
        this.clientePjs = clientePjs;
    }
    public Set getClientePfs() {
        return this.clientePfs;
    }
    
    public void setClientePfs(Set clientePfs) {
        this.clientePfs = clientePfs;
    }




}


