package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Processo generated by hbm2java
 */
public class Processo  implements java.io.Serializable {


     private Integer id;
     private Advogado advogado;
     private String outrosEnvolvidos;
     private String titulo;
     private int numeroProcesso;
     private int juizoNum;
     private String juizoVara;
     private String juizoForo;
     private String nomeAcao;
     private double valorCausa;
     private Date distribuido;
     private String movimentacao;
     private Set tblProcessoPjs = new HashSet(0);
     private Set tblProcessoPfs = new HashSet(0);
     private Set agendas = new HashSet(0);
     private Set financeiros = new HashSet(0);

    public Processo() {
    }

	
    public Processo(Advogado advogado, String titulo, int numeroProcesso, int juizoNum, String juizoVara, String juizoForo, String nomeAcao, double valorCausa, Date distribuido) {
        this.advogado = advogado;
        this.titulo = titulo;
        this.numeroProcesso = numeroProcesso;
        this.juizoNum = juizoNum;
        this.juizoVara = juizoVara;
        this.juizoForo = juizoForo;
        this.nomeAcao = nomeAcao;
        this.valorCausa = valorCausa;
        this.distribuido = distribuido;
    }
    public Processo(Advogado advogado, String outrosEnvolvidos, String titulo, int numeroProcesso, int juizoNum, String juizoVara, String juizoForo, String nomeAcao, double valorCausa, Date distribuido, String movimentacao) {
       this.advogado = advogado;
       this.outrosEnvolvidos = outrosEnvolvidos;
       this.titulo = titulo;
       this.numeroProcesso = numeroProcesso;
       this.juizoNum = juizoNum;
       this.juizoVara = juizoVara;
       this.juizoForo = juizoForo;
       this.nomeAcao = nomeAcao;
       this.valorCausa = valorCausa;
       this.distribuido = distribuido;
       this.movimentacao = movimentacao;
    }
    
    public Processo(Advogado advogado, String outrosEnvolvidos, String titulo, int numeroProcesso, int juizoNum, String juizoVara, String juizoForo, String nomeAcao, double valorCausa, Date distribuido, String movimentacao, Set tblProcessoPjs, Set tblProcessoPfs, Set agendas, Set financeiros) {
       this.advogado = advogado;
       this.outrosEnvolvidos = outrosEnvolvidos;
       this.titulo = titulo;
       this.numeroProcesso = numeroProcesso;
       this.juizoNum = juizoNum;
       this.juizoVara = juizoVara;
       this.juizoForo = juizoForo;
       this.nomeAcao = nomeAcao;
       this.valorCausa = valorCausa;
       this.distribuido = distribuido;
       this.movimentacao = movimentacao;
       this.tblProcessoPjs = tblProcessoPjs;
       this.tblProcessoPfs = tblProcessoPfs;
       this.agendas = agendas;
       this.financeiros = financeiros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Advogado getAdvogado() {
        return this.advogado;
    }
    
    public void setAdvogado(Advogado advogado) {
        this.advogado = advogado;
    }
    public String getOutrosEnvolvidos() {
        return this.outrosEnvolvidos;
    }
    
    public void setOutrosEnvolvidos(String outrosEnvolvidos) {
        this.outrosEnvolvidos = outrosEnvolvidos;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getNumeroProcesso() {
        return this.numeroProcesso;
    }
    
    public void setNumeroProcesso(int numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
    }
    public int getJuizoNum() {
        return this.juizoNum;
    }
    
    public void setJuizoNum(int juizoNum) {
        this.juizoNum = juizoNum;
    }
    public String getJuizoVara() {
        return this.juizoVara;
    }
    
    public void setJuizoVara(String juizoVara) {
        this.juizoVara = juizoVara;
    }
    public String getJuizoForo() {
        return this.juizoForo;
    }
    
    public void setJuizoForo(String juizoForo) {
        this.juizoForo = juizoForo;
    }
    public String getNomeAcao() {
        return this.nomeAcao;
    }
    
    public void setNomeAcao(String nomeAcao) {
        this.nomeAcao = nomeAcao;
    }
    public double getValorCausa() {
        return this.valorCausa;
    }
    
    public void setValorCausa(double valorCausa) {
        this.valorCausa = valorCausa;
    }
    public Date getDistribuido() {
        return this.distribuido;
    }
    
    public void setDistribuido(Date distribuido) {
        this.distribuido = distribuido;
    }
    public String getMovimentacao() {
        return this.movimentacao;
    }
    
    public void setMovimentacao(String movimentacao) {
        this.movimentacao = movimentacao;
    }
    public Set getTblProcessoPjs() {
        return this.tblProcessoPjs;
    }
    
    public void setTblProcessoPjs(Set tblProcessoPjs) {
        this.tblProcessoPjs = tblProcessoPjs;
    }
    public Set getTblProcessoPfs() {
        return this.tblProcessoPfs;
    }
    
    public void setTblProcessoPfs(Set tblProcessoPfs) {
        this.tblProcessoPfs = tblProcessoPfs;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }
    public Set getFinanceiros() {
        return this.financeiros;
    }
    
    public void setFinanceiros(Set financeiros) {
        this.financeiros = financeiros;
    }




}


