package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAgendaPfId generated by hbm2java
 */
public class TblAgendaPfId  implements java.io.Serializable {


     private int clientePfId;
     private int agendaId;

    public TblAgendaPfId() {
    }

    public TblAgendaPfId(int clientePfId, int agendaId) {
       this.clientePfId = clientePfId;
       this.agendaId = agendaId;
    }
   
    public int getClientePfId() {
        return this.clientePfId;
    }
    
    public void setClientePfId(int clientePfId) {
        this.clientePfId = clientePfId;
    }
    public int getAgendaId() {
        return this.agendaId;
    }
    
    public void setAgendaId(int agendaId) {
        this.agendaId = agendaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAgendaPfId) ) return false;
		 TblAgendaPfId castOther = ( TblAgendaPfId ) other; 
         
		 return (this.getClientePfId()==castOther.getClientePfId())
 && (this.getAgendaId()==castOther.getAgendaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClientePfId();
         result = 37 * result + this.getAgendaId();
         return result;
   }   


}


