package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAdvCpf generated by hbm2java
 */
public class TblAdvCpf  implements java.io.Serializable {

    private TblAdvCpfId id;
    private Advogado advogado;
    private ClientePf clientePf;

    public TblAdvCpf() {
    }

    public TblAdvCpf(TblAdvCpfId id, Advogado advogado, ClientePf clientePf) {
       this.id = id;
       this.advogado = advogado;
       this.clientePf = clientePf;
    }
   
    public TblAdvCpfId getId() {
        return this.id;
    }
    
    public void setId(TblAdvCpfId id) {
        this.id = id;
    }
    public Advogado getAdvogado() {
        return this.advogado;
    }
    
    public void setAdvogado(Advogado advogado) {
        this.advogado = advogado;
    }
    public ClientePf getClientePf() {
        return this.clientePf;
    }
    
    public void setClientePf(ClientePf clientePf) {
        this.clientePf = clientePf;
    }




}


