package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAdvCpjId generated by hbm2java
 */
public class TblAdvCpjId  implements java.io.Serializable {


     private int advogadoId;
     private int clientePjId;

    public TblAdvCpjId() {
    }

    public TblAdvCpjId(int advogadoId, int clientePjId) {
       this.advogadoId = advogadoId;
       this.clientePjId = clientePjId;
    }
   
    public int getAdvogadoId() {
        return this.advogadoId;
    }
    
    public void setAdvogadoId(int advogadoId) {
        this.advogadoId = advogadoId;
    }
    public int getClientePjId() {
        return this.clientePjId;
    }
    
    public void setClientePjId(int clientePjId) {
        this.clientePjId = clientePjId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAdvCpjId) ) return false;
		 TblAdvCpjId castOther = ( TblAdvCpjId ) other; 
         
		 return (this.getAdvogadoId()==castOther.getAdvogadoId())
 && (this.getClientePjId()==castOther.getClientePjId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdvogadoId();
         result = 37 * result + this.getClientePjId();
         return result;
   }   


}


