package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAgendaPf generated by hbm2java
 */
public class TblAgendaPf  implements java.io.Serializable {


     private TblAgendaPfId id;
     private Agenda agenda;
     private ClientePf clientePf;

    public TblAgendaPf() {
    }
    
    public String[] getAgendatbl(){
        return new String[]{
            String.valueOf(agenda.getId()),
            clientePf.getNome(),
            String.valueOf(agenda.getData()),
            String.valueOf(agenda.getHora()),
            agenda.getDetalhes(),
            agenda.getLocal()
        };
    }

    public TblAgendaPf(TblAgendaPfId id, Agenda agenda, ClientePf clientePf) {
       this.id = id;
       this.agenda = agenda;
       this.clientePf = clientePf;
    }
   
    public TblAgendaPfId getId() {
        return this.id;
    }
    
    public void setId(TblAgendaPfId id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public ClientePf getClientePf() {
        return this.clientePf;
    }
    
    public void setClientePf(ClientePf clientePf) {
        this.clientePf = clientePf;
    }




}


