package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAgendaPjId generated by hbm2java
 */
public class TblAgendaPjId  implements java.io.Serializable {


     private int agendaId;
     private int clientePjId;

    public TblAgendaPjId() {
    }

    public TblAgendaPjId(int agendaId, int clientePjId) {
       this.agendaId = agendaId;
       this.clientePjId = clientePjId;
    }
   
    public int getAgendaId() {
        return this.agendaId;
    }
    
    public void setAgendaId(int agendaId) {
        this.agendaId = agendaId;
    }
    public int getClientePjId() {
        return this.clientePjId;
    }
    
    public void setClientePjId(int clientePjId) {
        this.clientePjId = clientePjId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAgendaPjId) ) return false;
		 TblAgendaPjId castOther = ( TblAgendaPjId ) other; 
         
		 return (this.getAgendaId()==castOther.getAgendaId())
 && (this.getClientePjId()==castOther.getClientePjId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAgendaId();
         result = 37 * result + this.getClientePjId();
         return result;
   }   


}


