package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAdvCpfId generated by hbm2java
 */
public class TblAdvCpfId  implements java.io.Serializable {


     private int advogadoId;
     private int clientePfId;

    public TblAdvCpfId() {
    }

    public TblAdvCpfId(int advogadoId, int clientePfId) {
       this.advogadoId = advogadoId;
       this.clientePfId = clientePfId;
    }
   
    public int getAdvogadoId() {
        return this.advogadoId;
    }
    
    public void setAdvogadoId(int advogadoId) {
        this.advogadoId = advogadoId;
    }
    public int getClientePfId() {
        return this.clientePfId;
    }
    
    public void setClientePfId(int clientePfId) {
        this.clientePfId = clientePfId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAdvCpfId) ) return false;
		 TblAdvCpfId castOther = ( TblAdvCpfId ) other; 
         
		 return (this.getAdvogadoId()==castOther.getAdvogadoId())
 && (this.getClientePfId()==castOther.getClientePfId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdvogadoId();
         result = 37 * result + this.getClientePfId();
         return result;
   }   


}


