package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblAdvCpj generated by hbm2java
 */
public class TblAdvCpj  implements java.io.Serializable {


     private TblAdvCpjId id;
     private Advogado advogado;
     private ClientePj clientePj;

    public TblAdvCpj() {
    }

    public TblAdvCpj(TblAdvCpjId id, Advogado advogado, ClientePj clientePj) {
       this.id = id;
       this.advogado = advogado;
       this.clientePj = clientePj;
    }
   
    public TblAdvCpjId getId() {
        return this.id;
    }
    
    public void setId(TblAdvCpjId id) {
        this.id = id;
    }
    public Advogado getAdvogado() {
        return this.advogado;
    }
    
    public void setAdvogado(Advogado advogado) {
        this.advogado = advogado;
    }
    public ClientePj getClientePj() {
        return this.clientePj;
    }
    
    public void setClientePj(ClientePj clientePj) {
        this.clientePj = clientePj;
    }




}


