package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblFinanceiroPfId generated by hbm2java
 */
public class TblFinanceiroPfId  implements java.io.Serializable {


     private int clientePfId;
     private int financeiroId;

    public TblFinanceiroPfId() {
    }

    public TblFinanceiroPfId(int clientePfId, int financeiroId) {
       this.clientePfId = clientePfId;
       this.financeiroId = financeiroId;
    }
   
    public int getClientePfId() {
        return this.clientePfId;
    }
    
    public void setClientePfId(int clientePfId) {
        this.clientePfId = clientePfId;
    }
    public int getFinanceiroId() {
        return this.financeiroId;
    }
    
    public void setFinanceiroId(int financeiroId) {
        this.financeiroId = financeiroId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblFinanceiroPfId) ) return false;
		 TblFinanceiroPfId castOther = ( TblFinanceiroPfId ) other; 
         
		 return (this.getClientePfId()==castOther.getClientePfId())
 && (this.getFinanceiroId()==castOther.getFinanceiroId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClientePfId();
         result = 37 * result + this.getFinanceiroId();
         return result;
   }   


}


