package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblFinanceiroPj generated by hbm2java
 */
public class TblFinanceiroPj  implements java.io.Serializable {


     private TblFinanceiroPjId id;
     private ClientePj clientePj;
     private Financeiro financeiro;

    public TblFinanceiroPj() {
    }
    
    public String[] getFinanceirotbl(){
        return new String[]{
            String.valueOf(financeiro.getId()),
            String.valueOf(financeiro.getTipo()),
            String.valueOf(financeiro.getFuturo()),
            String.valueOf(financeiro.getPresente()),
            clientePj.getNomeFantasia(),
            financeiro.getDescricao(),
            financeiro.getParcelaString(),
            String.valueOf(financeiro.getValor())
        };
    }

    public TblFinanceiroPj(TblFinanceiroPjId id, ClientePj clientePj, Financeiro financeiro) {
       this.id = id;
       this.clientePj = clientePj;
       this.financeiro = financeiro;
    }
   
    public TblFinanceiroPjId getId() {
        return this.id;
    }
    
    public void setId(TblFinanceiroPjId id) {
        this.id = id;
    }
    public ClientePj getClientePj() {
        return this.clientePj;
    }
    
    public void setClientePj(ClientePj clientePj) {
        this.clientePj = clientePj;
    }
    public Financeiro getFinanceiro() {
        return this.financeiro;
    }
    
    public void setFinanceiro(Financeiro financeiro) {
        this.financeiro = financeiro;
    }




}


