package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblProcessoPjId generated by hbm2java
 */
public class TblProcessoPjId  implements java.io.Serializable {


     private int processoId;
     private int clientePjId;

    public TblProcessoPjId() {
    }

    public TblProcessoPjId(int processoId, int clientePjId) {
       this.processoId = processoId;
       this.clientePjId = clientePjId;
    }
   
    public int getProcessoId() {
        return this.processoId;
    }
    
    public void setProcessoId(int processoId) {
        this.processoId = processoId;
    }
    public int getClientePjId() {
        return this.clientePjId;
    }
    
    public void setClientePjId(int clientePjId) {
        this.clientePjId = clientePjId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblProcessoPjId) ) return false;
		 TblProcessoPjId castOther = ( TblProcessoPjId ) other; 
         
		 return (this.getProcessoId()==castOther.getProcessoId())
 && (this.getClientePjId()==castOther.getClientePjId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProcessoId();
         result = 37 * result + this.getClientePjId();
         return result;
   }   


}


