package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblProcessoPf generated by hbm2java
 */
public class TblProcessoPf  implements java.io.Serializable {


     private TblProcessoPfId id;
     private ClientePf clientePf;
     private Processo processo;

    public TblProcessoPf() {
    }
    
    public String[] getProcessotbl(){
        return new String[]{
            String.valueOf(processo.getId()),
            clientePf.getNome(),
            String.valueOf(processo.getTitulo()),
            String.valueOf(processo.getNomeAcao()),
            String.valueOf(processo.getValorCausa()),
            String.valueOf(processo.getDistribuido())
        };
    }

    public TblProcessoPf(TblProcessoPfId id, ClientePf clientePf, Processo processo) {
       this.id = id;
       this.clientePf = clientePf;
       this.processo = processo;
    }
   
    public TblProcessoPfId getId() {
        return this.id;
    }
    
    public void setId(TblProcessoPfId id) {
        this.id = id;
    }
    public ClientePf getClientePf() {
        return this.clientePf;
    }
    
    public void setClientePf(ClientePf clientePf) {
        this.clientePf = clientePf;
    }
    public Processo getProcesso() {
        return this.processo;
    }
    
    public void setProcesso(Processo processo) {
        this.processo = processo;
    }




}


