package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblProcessoPfId generated by hbm2java
 */
public class TblProcessoPfId  implements java.io.Serializable {


     private int processoId;
     private int clientePfId;

    public TblProcessoPfId() {
    }

    public TblProcessoPfId(int processoId, int clientePfId) {
       this.processoId = processoId;
       this.clientePfId = clientePfId;
    }
   
    public int getProcessoId() {
        return this.processoId;
    }
    
    public void setProcessoId(int processoId) {
        this.processoId = processoId;
    }
    public int getClientePfId() {
        return this.clientePfId;
    }
    
    public void setClientePfId(int clientePfId) {
        this.clientePfId = clientePfId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblProcessoPfId) ) return false;
		 TblProcessoPfId castOther = ( TblProcessoPfId ) other; 
         
		 return (this.getProcessoId()==castOther.getProcessoId())
 && (this.getClientePfId()==castOther.getClientePfId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProcessoId();
         result = 37 * result + this.getClientePfId();
         return result;
   }   


}


