package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1



/**
 * TblProcessoPj generated by hbm2java
 */
public class TblProcessoPj  implements java.io.Serializable {


     private TblProcessoPjId id;
     private ClientePj clientePj;
     private Processo processo;

    public TblProcessoPj() {
    }
    
    public String[] getProcessotbl(){
        return new String[]{
            String.valueOf(processo.getId()),
            clientePj.getNomeFantasia(),
            String.valueOf(processo.getTitulo()),
            String.valueOf(processo.getNomeAcao()),
            String.valueOf(processo.getValorCausa()),
            String.valueOf(processo.getDistribuido())
        };
    }

    public TblProcessoPj(TblProcessoPjId id, ClientePj clientePj, Processo processo) {
       this.id = id;
       this.clientePj = clientePj;
       this.processo = processo;
    }
   
    public TblProcessoPjId getId() {
        return this.id;
    }
    
    public void setId(TblProcessoPjId id) {
        this.id = id;
    }
    public ClientePj getClientePj() {
        return this.clientePj;
    }
    
    public void setClientePj(ClientePj clientePj) {
        this.clientePj = clientePj;
    }
    public Processo getProcesso() {
        return this.processo;
    }
    
    public void setProcesso(Processo processo) {
        this.processo = processo;
    }




}


