package control;
// Generated 24/11/2017 02:51:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {

    private Integer id;
    private String login;
    private String senha;
    private char cargo;
    private byte ativo;
    private String acesso;
    private Set funcionarios = new HashSet(0);
    private Set advogados = new HashSet(0);

    public Usuarios() {
    }
    
    public String[] getUsuarios(){
        return new String[]{
            String.valueOf(id),
            login,
            senha,
            getCargo()=='E'?"Estagiario(a)":"Secretário(a)",
            String.valueOf(getAtivo()==1)
        };
    }
	
    public Usuarios(String login, String senha, char cargo, byte ativo, String cadastros, String relatorios, String agenda, String processo, String financeiro) {
        this.login = login;
        this.senha = senha;
        this.cargo = cargo;
        this.ativo = ativo;
        this.acesso = "";
        this.acesso +=cadastros;
        this.acesso +=relatorios;
        this.acesso +=agenda;
        this.acesso +=processo;
        this.acesso +=financeiro;
    }
    public Usuarios(String login, String senha, char cargo, byte ativo, String acesso, Set funcionarios, Set advogados) {
       this.login = login;
       this.senha = senha;
       this.cargo = cargo;
       this.ativo = ativo;
       this.acesso = acesso;
       this.funcionarios = funcionarios;
       this.advogados = advogados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public char getCargo() {
        return this.cargo;
    }
    
    public void setCargo(char cargo) {
        this.cargo = cargo;
    }
    public byte getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(byte ativo) {
        this.ativo = ativo;
    }
    public String getAcesso() {
        return this.acesso;
    }
    
    public void setAcesso(String acesso) {
        this.acesso = acesso;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getAdvogados() {
        return this.advogados;
    }
    
    public void setAdvogados(Set advogados) {
        this.advogados = advogados;
    }




}


